Repository meshery/meshery-consul, pull requests merged in 2022-09, with the labels that each got.

#302 Add Event streamer struct
  consul/consul.go
  consul/oam.go
  consul/operations.go
  go.mod
  go.sum
  main.go
Labels: area/lifecycle

#308 Pending upgrade from Go 1.17 to 1.19
  .github/workflows/ci.yml
  .github/workflows/update-oam-defs.yml
  .golangci.yml
  Dockerfile
  Makefile
  build/Makefile.core.mk
  build/config.go
  consul/consul.go
  go.mod
  go.sum
Labels: language/go

#315 [chore] Update deprecated ioutil import
  internal/config/releases.go
Labels: kind/chore, language/go

#314 [chore] Update Adapter Build files
  .github/workflows/multi-platform.yml
  Dockerfile
  Makefile
Labels: kind/bug, kind/chore, area/ci
